dependencies:
  - OpenZeppelin/openzeppelin-contracts@2.5.0
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@2.5.0"

networks:
  default: development

dotenv: .env

wallets:
  from_key: ${PRIVATE_KEY}